// Generated by https://app.quicktype.io/

namespace ReBalanced.Infastructure.MBoum;

public class CoinQuote
    {
        public Meta? Meta { get; set; }
        public CoinData? Data { get; set; }
    }

    public class CoinData
    {
        public decimal Price { get; set; }
        public decimal PriceChangePercentage1H { get; set; }
        public decimal PriceChangePercentage24H { get; set; }
        public decimal PriceChangePercentage7D { get; set; }
        public decimal PriceChangePercentage30D { get; set; }
        public decimal PriceChangePercentage60D { get; set; }
        public decimal PriceChangePercentage90D { get; set; }
        public decimal MarketCap { get; set; }
        public decimal MarketCapChangePercentage24H { get; set; }
        public decimal FullyDilutedMarketCap { get; set; }
        public decimal FullyDilutedMarketCapChangePercentage24H { get; set; }
        public long CirculatingSupply { get; set; }
        public long TotalSupply { get; set; }
        public long MaxSupply { get; set; }
        public decimal MarketCapDominance { get; set; }
        public long Rank { get; set; }
        public decimal Roi { get; set; }
        public decimal Low24H { get; set; }
        public decimal High24H { get; set; }
        public decimal Low7D { get; set; }
        public decimal High7D { get; set; }
        public decimal Low30D { get; set; }
        public decimal High30D { get; set; }
        public decimal Low90D { get; set; }
        public decimal High90D { get; set; }
        public decimal Low52W { get; set; }
        public decimal High52W { get; set; }
        public decimal LowAllTime { get; set; }
        public decimal HighAllTime { get; set; }
        public decimal LowAllTimeChangePercentage { get; set; }
        public decimal HighAllTimeChangePercentage { get; set; }
        public DateTimeOffset LowAllTimeTimestamp { get; set; }
        public DateTimeOffset HighAllTimeTimestamp { get; set; }
        public decimal LowYesterday { get; set; }
        public decimal HighYesterday { get; set; }
        public decimal OpenYesterday { get; set; }
        public decimal CloseYesterday { get; set; }
        public decimal PriceChangePercentageYesterday { get; set; }
        public decimal VolumeYesterday { get; set; }
        public decimal Turnover { get; set; }
        public decimal YtdPriceChangePercentage { get; set; }
        public string? Status { get; set; }
        public decimal Volume { get; set; }
        public decimal VolumeChangePercentage24H { get; set; }
    }